---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean

.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: swift
      entrypoint: ["/init_ci.sh"]
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update py3-pip
    - pip install --break-system-packages python-swiftclient
  variables:
    GIT_STRATEGY: none
  dependencies: []

OpenStack Swift:
  stage: Test
  extends: .services
  script:
    - swift -T 5 -R 1 -A http://swift:8080/auth/v1.0 -U test:tester -K testing list test # DevSkim: ignore DS137138
